### ISSUE TITLE
Non-model species

### ISSUE THREAD

**Issue by guandailu** [hoffmangroup/virchip#2]
Very nice tool, I wondering if the tool can be used in non-model species, such as cattle, chicken, pig etc.?

**Comment by mehrankr** [comment]
Hello @guandailu 

Virtual ChIP-seq requires matched data from various sources to train, and therefore it has only been trained for the human genome. There are other tools, however, which can provide cell-type–agnostic predictions of various genomic signals for any DNA sequence (e.g. Enformer https://www.nature.com/articles/s41592-021-01252-x). Those might be more applicable to other species, even though they are still trained on only human or mice data.

**Comment by michaelmhoffman** [comment]
Yes, to run Virtual ChIP-seq as described in the paper, you need ChIP-seq data for the same DNA-binding protein in different cell types for the same species. Model organisms (and particularly model mammalian organisms, thanks to ENCODE) just are more likely to have such data available already. You could certainly generate ChIP-seq data for several cow cell types and then predict on others.
